language: python

sudo: required

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
#  - "pypy"

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r test/requirements.txt

script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer python3
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - pip install --upgrade pip
  - ONLINE=1 ./bau test

after_script:
  - codecov
